name: LilyHub
author: sgtcaze
main: com.sgtcaze.LilyHub.Main
version: 3.1
depend: [LilyPad-Connect]

commands:
   hub:
    description: Command to get to the hub.
   lobby:
    description: Command to get to the hub.